server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql_department:3306/department_db
    username: gibbssonfarias
    password: gibb246
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/