server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres_employee:5432/employee_db
    username: gibbssonfarias
    password: gibb246
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/